### ISSUE TITLE
ERROR::/Dobot Magician/Other/Unhandled Exception

### ISSUE THREAD

**Issue by fykey** [jkaniuka/magician_ros2#5] opened 2024-01-09 12:40 UTC
Hi！

I am running Dobot Magician on Ubuntu22.04 on VM Virtual box.
The environment is as follows.

Ubuntu 22.04
ROS2 humble
memory:8GB
CPU 8 Core

I built it according to the read me, but when I checked it with command, `rqt -s rqt_robot_monitor`, the following error occurred.
```
"""
Full Name: /Dobot Magician/Other/Unhandled Exception
Component: Unhandled Exception
Hardware ID: 
Level: ERROR
Message: EXCEPTION CODES: 0
"""
Description: These alarms are software related, not hardware related, and are handled by another part of the control system. If such an alarm appeared, it is best to restart and re-power the robot and notify the maintainer of the package about it (by e-mail or via GitHub).
Quick fix: Check alarm code in Dobot-Magician-ALARM-Description.pdf document and follow the recommendations
```

When I perform an action, it is rejected as shown below.
```
$ ros2 action send_goal /PTP_action  dobot_msgs/action/PointToPoint "{motion_type: 1, target_pose: [200.0, 0.0, 100.0, 0.0], velocity_ratio: 0.5, acceleration_ratio: 0.3}" --feedback


Waiting for an action server to become available...
Sending goal:
     motion_type: 1
target_pose:
- 200.0
- 0.0
- 100.0
- 0.0
velocity_ratio: 0.5
acceleration_ratio: 0.3

Goal was rejected.
```

The following log is generated in the other terminal. (Actual LED is green)
```
[ros2 launch dobot_motion dobot_PTP.launch.py-7] [PTP_server-1] [WARN] [1704802521.865999757] [dobot_PTP_server]: Goal rejected because of active alarms (LED diode in the robot base lights up red)
```

If you know how to deal with it, please let me know.
I apologize for my poor English and issue. Thank you for your support.

**Comment by jkaniuka** [comment] 2024-01-10 21:09
Hi @fykey :wave:, thanks for letting me know about this issue. I have a suspicion what might be the cause of this bug. I will be working with Dobot Magician next Monday, I will try to fix it and will let you know right away.

**Comment by jkaniuka** [comment] 2024-01-16 23:26
Fixes that could probably solve your problem were added in a fork of this repo, so please follow the steps below:
1. Clone forked repo with fixes:
```bash
git clone https://github.com/GroupOfRobots/magician_ros2.git -b fszyszko2
```
2. Build packages and start control system
```bash
ros2 launch dobot_bringup dobot_magician_control_system.launch.py
```
3. After the control stack has been launched, make a call to _dobot_alarm_clear_service_ service:
```bash
ros2 service call /dobot_alarm_clear_service dobot_msgs/srv/ExecuteAlarmClear
```
4. Check alarm codes in Diagnostics Viewer.
5. If there's no active alarms, try to send goal to _PTP_action_ action server.

Please let me know if this resolves your issue :wink:

**Comment by jkaniuka** [comment] 2024-02-12 11:48
@fykey Any update? :thinking:

**Comment by jkaniuka** [comment] 2024-04-15 19:21
Please reopen if you still encounter this issue. Closing for now.

**Closed as not planned by jkaniuka** 2024-04-15 19:21 UTC
Labels: bug
